### PR TITLE
Updated translations

### PR DESCRIPTION
**Pull request by devs-mycroft**
Automatically generated PR from translate.mycroft.ai

The updated languages are:
- sv-se
- de-de
- fr-fr
- ru-ru
- es-es
- es-lm
- nl-nl
- pt-br
- it-it
- da-dk

### CODE REVIEW

**Comment by Tony763** [comment]
Hi @krisgesling, This PR contain double brackets `{{` that were removed in PR #71.

**Comment by Tony763** [comment]
Also second utterance in   `de-de/homeassistant.device.off.dialog`  has unbalanced number of brackets.
```
{{dev_name}} abgedreht.
{dev_name}} wurde ausgeschaltet.
{{dev_name}} ist jetzt ausgeschaltet.
```

`dialog/da-dk/homeassistant.device.unknown.dialog` have variables enclosed in `"`. 
```
Entitet "{{dev_name}}" kunne ikke findes.
```

Also some dialogs and intents were removed :scream:.

**Comment by krisgesling** [comment]
Yeah, if these aren't updated in translate.mycroft.ai it will always push the double brackets again. Currently there's no two-way sync with translate. It's English > Translations > Skills

We certainly don't have to merge this, particularly given it has those unbalanced brackets, but we'll need to think of how we want to handle this into the future.

**Comment by stratus-ss** [comment]
I'm closing this down due to the issues that @Tony763 brought up.

**Pull request closed without merging**
