### PR TITLE
20.02 fix fallback

### PR DESCRIPTION
**Pull request by andlo**
## Description:

**Related issue (if applicable):** fixes #<mycroft-homeassistant issue number goes here>
#23 

## Checklist:
  - [X] Code is Python 3.x compatible
  - [X] Travis is passing tests **Your PR cannot be merged unless tests pass**
  - [X] No PEP Bot Errors or Issues

### CODE REVIEW

**Comment by forslund** [comment]
This looks good as far as I can see. I don't use homeassistant myself so I can't render a final judgement.

Has anyone else tried it?

**Comment by andlo** [comment]
Yah a user in homeassistant forum did confirm. Around middel of the conversation...

https://community.home-assistant.io/t/homeassistant-skill-for-mycroft/73347/11

But other than that I dont know.

**Comment by andlo** [comment]
Ohhh also confirmed in issue #23
https://github.com/MycroftAI/mycroft-homeassistant/issues/23

**Comment by forslund** [comment]
Excellent, then I won't stand in the way of progress!

Tusind tak!

**Pull request merged**
