### PR TITLE
Add padatious intents for turn on, turn off and toggle actions.

### LINKED ISSUE #25: Language issue
Hello,

I'm trying to use the skill and it works perfectly in English. However in french (configured by "lang": "fr-fr", in mycroft.conf), no keywords work. For instance I use "allume XXX" which is the equivalent to "turn on XXX" (according to this https://translate.mycroft.ai/fr/mycroft-skills/translate/homeassistant-fr.po#search=allume&sfields=source,target&unit=134631&offset=0) but faced with a blank response "Sorry I don't understand".

Logs are below.

Anything I'm doing wrong to change language?

Thanks

```
 10:52:23.476 | DEBUG    |   675 | mycroft.skills.intent_service:handle_utterance:329 | Utterances: ['allume entree']
~~~~lls.intent_service:handle_utterance:349 | Padatious intent: {'name': 'mycroft-stop.mycroftai:reboot.intent', 'sent': 'allume entree', 'matches': {}, 'conf': 0.17207702686938922}
 10:52:23.584 | DEBUG    |   675 | mycroft.skills.intent_service:handle_utterance:350 |     Adapt intent: None
 10:52:23.592 | DEBUG    |   675 | mycroft.skills.padatious_service:handle_fallback:157 | Padatious fallback attempt: allume entree
 10:52:23.593 | INFO     |   675 | QuestionsAnswersSkill | Searching for allume entree
 10:52:23.597 | DEBUG    |   675 | mycroft.skills.mycroft_skill.event_container:add:146 | Added event: fallback-query.mycroftai:QuestionQueryTimeout
 10:52:23.648 | DEBUG    |   675 | WolframAlphaSkill | WolframAlpha query: allume entree
Removing event fallback-query.mycroftai:QuestionQueryTimeout
 10:52:23.658 | DEBUG    |   675 | mycroft.skills.mycroft_skill.event_container:add:146 | Added event: fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
 10:52:23.663 | DEBUG    |   675 | mycroft.skills.mycroft_skill.event_container:add:146 | Added event: fallback-query.mycroftai:QuestionQueryTimeout
 10:52:23.703 | DEBUG    |   675 | WolframAlphaSkill | translation: light entry
 10:52:23.704 | DEBUG    |   675 | WolframAlphaSkill | Non-question, ignoring: light entry
Removing event fallback-query.mycroftai:QuestionQueryTimeout
 10:52:23.749 | DEBUG    |   675 | mycroft.skills.mycroft_skill.event_container:add:146 | Added event: fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
10:52:24.191 | INFO     |   675 | QuestionsAnswersSkill | Timeout occured check responses
 10:52:24.600 | DEBUG    |   675 | mycroft.skills.padatious_service:handle_fallback:157 | Padatious fallback attempt: allume entree
 10:52:30.103 | DEBUG    |   675 | urllib3.connectionpool | Starting new HTTPS connection (1): api.mycroft.ai:443
 10:52:30.468 | DEBUG    |   675 | urllib3.connectionpool | https://api.mycroft.ai:443 "GET /v1/device/aa930e2b-a455-40d8-840e-b25d3be1e668/skill/settings HTTP/1.1" 304 0
 10:52:30.475 | DEBUG    |   675 | mycroft.skills.settings:download:365 | No skill settings changes since last download
 10:53:07.251 | DEBUG    |   675 | urllib3.connectionpool | Starting new HTTPS connection (1): api.mycroft.ai:443
 10:53:07.622 | DEBUG    |   675 | urllib3.connectionpool | https://api.mycroft.ai:443 "GET /v1/device/aa930e2b-a455-40d8-840e-b25d3be1e668/setting HTTP/1.1" 304 0
 10:53:07.630 | DEBUG    |   675 | urllib3.connectionpool | Starting new HTTPS connection (1): api.mycroft.ai:443
 10:53:07.984 | DEBUG    |   675 | urllib3.connectionpool | https://api.mycroft.ai:443 "GET /v1/device/aa930e2b-a455-40d8-840e-b25d3be1e668/location HTTP/1.1" 304 0
  ^--- NEWEST ---^ 

```

### PR DESCRIPTION
**Pull request by kamir86**
## Description:
Add padatious intents for several actions. Language supported: english, italian, czech and geman, thanks to @Tony763 and @Manasovo . 
This fixes several intents, that're not working on 20.02 in several languages outside english.
See my first comment: on issue #25

Changes:
- Rewrited turn on adapt intent to Padatious
- Rewrited turn off adapt intent to Padatious
- Rewrited toggle adapt intent to Padatious
- Rewrited sensor adapt intent to Padatious
- Rewrited set light adapt intent to Padatious
- Initial czech support
- Added quantulum3 to requirements (a crash was spotted during the fix)

**Related issue (if applicable):** fixes #25 Italian english czech and geman, thanks to @Tony763 and @Manasovo  , I need some support for other languages

## Checklist:
  - [X] Code is Python 3.x compatible
  - [ ] Travis is passing tests **Your PR cannot be merged unless tests pass**
  - [X] No PEP Bot Errors or Issues

### CODE REVIEW

**Review by stratus-ss — COMMENTED** [review]
Thanks for the PR, sorry it took me so long to get around to this. I dug into the project after this was submitted and didn't realize it was pending.

I need to test this myself, but in general this is not a bad idea. One reason that we may want to stick with Adept is if we have reason to believe that conversational contexts will be used either now or in the future.

What are your thoughts on needing conversational contexts with the HA skill?
As a finaly note, PR #41 has been approved and may cause a conflict starting around line 248. 

Thanks again for the PR, you can also reach out on the Mycroft mattermost instance

**Comment by kamir86** [comment]
Hello, thanks for your reply. 
I think that a popular issue should not remain unfixed for a maybe future development in the future. Mycroft will eventually support conversational contexts in padatious intents too. I'm not in the development team but it's clearly stated in the skill guide. 
I'm open to stick with adapt intent to fix this, but the fix won't be easy and a lot of language specific code should be added, mind of the current de-de support.

**Comment by stratus-ss** [comment]
> I think that a popular issue should not remain unfixed for a maybe future development in the future. 

This is a fair point. I like using Padatious intents for their simplicity and I can see why you would want to do this for additional language support.

> I'm open to stick with adapt intent to fix this, but the fix won't be easy and a lot of language specific code should be added, mind of the current de-de support.

With this in mind I think your proposal has merit. It will pend testing and PR #41 but other than that I think the idea is sound and your rationale is good. Thanks for the fix. Someone will try to get this tested soon. I'm going to try and be more on top of this repo going forward

**Comment by stratus-ss** [comment]
@kamir86 PR #41 was approved and merged. I came back to look at this one and see there is a conflict now. Would you mind seeing if you can address the conflict?

Thanks

**Comment by kamir86** [comment]
Hello, I'll check  this as soon as i can

**Comment by stratus-ss** [comment]
Thanks for the update. I'll be ready to try this, this week. I've looked over the the diffs. Its just a matter of testing the changes.

Do you have sample sentences I can try with the expected results.

I'm sure I can figure it out from the diffs, but it would be helpful to have the phrases you tested with

**Review by stratus-ss — APPROVED** [review]
LGTM. @krisgesling and I went through this and it tested ok for me

**Comment by kamir86** [comment]
Hello thanks for merging this.
Sorry for the late response, i can provide some italian test sentences if you want to integrate your tests:
Turn on intent: 
Accendi la luce della sala.
Accendi l'interruttore dello studio.
Turn off intent: 
Spegni la luce della sala.
Spegni l'interruttore dello studio.
Toggle intent:
Commuta la luce della sala.
Commuta l'interruttore dello studio.
Increase brigthness intent:
Alza la luminosità della sala.
Rendi lo studio più luminoso.
Dec brigthness intent:
Abbassa la luminosità della sala.
Rendi lo studio meno luminoso.

**Comment by Tony763** [comment]
Hi @kamir86 as I know tests are possible only in English. I waiting for merging all my PRs as [Tests ](https://github.com/Tony763/mycroft-homeassistant/commit/63eeb057c816242d81bbbe2fe4ac23d033098aa8)are already prepared (in English),
also I have prepared a Travis testing solution.  
@stratus-ss is there a plan for adding support for other languages in Voight Kampff tests engine?

**Comment by kamir86** [comment]
hello @Tony763  thanks for adding english tests. 
It would be great to have tests in other languages ​​as well, this would prevent changes from producing defects, like the one this PR was addressed

**Comment by krisgesling** [comment]
@Tony763 @kamir86 - the issue for exploring this is at: https://github.com/MycroftAI/mycroft-core/issues/2552

**Pull request merged**
