### PR TITLE
README: Mention scripts and automations as supported

### LINKED ISSUE #118: The README doesn't mention scripts or automations
**Describe the bug**
The README lists the supported entity types, but doesn't mention scripts or automations. I almost opened a feature request to add these, but then found in the source code that they were in fact supported.

https://github.com/MycroftAI/skill-homeassistant/blob/c8853f9e471eb629341ce6440cc436a34724c5fd/__init__.py#L601

**To Reproduce**
n/a

**Expected behavior**
The README should document the actual features :)

**Log files**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by Ramblurr**
#### Description

Fixes #118

#### Type of PR

- [ ] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [x] Documentation improvements
- [ ] Test improvements

#### Testing
n/a

#### Documentation
It is a doc PR.

### CODE REVIEW

**Comment by Tony763** [comment]
Hi, good point. Just when You format entities as list, remove "and" before last type. :)

**Comment by Ramblurr** [comment]
That list of items is rendered all in one line in markdown (see the readme at https://github.com/Ramblurr/skill-homeassistant/tree/fix/update-readme). I split them into one line to make it easy to add new items in alphabetical order.. but when viewed in MD viewer it'll appear as one line:

image


Happy to change it still if you want me to.

**Comment by Tony763** [comment]
Ah, you are right. For the list, each line needs one of the prefixes (-, *, or +).

Just thinking that list would be better to read when more entities will be added. But it's just my option. ;)

**Review by stratus-ss — APPROVED** [review]
Approved. Thanks for the addition!

**Pull request merged**
