### PR TITLE
Fix issue #104 - Padatious intent and tracker list

### LINKED ISSUE #64: Intent conflicts for what and where
Submitting the latest Skill to the Marketplace showed there are some small intent conflicts with default Skills:
PR - https://github.com/MycroftAI/mycroft-skills/pull/1459
Voight Kampff report - https://reports.mycroft.ai/skills/PR-1459/

Primarily the utterances:
- what is the status of the chicken timer
- where is morocco
- where is saturn
- where is the smithsonian

It would be good to look at why this Skill is catching these utterances and improving intent handling so that we aren't trying to respond to utterances that don't relate to this Skill.

We could also add Voight Kampff tests for phrases that Home Assistant should not trigger on, like the above. Here's an example of that in the Timer Skill:
https://github.com/MycroftAI/mycroft-timer/blob/20.08/test/behave/timer.feature#L430

### PR DESCRIPTION
**Pull request by Tony763**
#### Description
PR contain workaround fixing #104 proposed by @zeronounours.
Proper fix (new functions) is awaiting approve/merge of PR [#3101](https://github.com/MycroftAI/mycroft-core/pull/3101).

As we want to update HA skill in Marketplace, it's better to use this workaround as proper fix can be incorporated later when PR is merged and new Mycroft Core is released. 

Credit goes to @zeronounours. Thanks mate.

Fixes #64 

#### Type of PR
- [x] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

### CODE REVIEW

**Comment by Tony763** [comment]
Reported as working by @robertsawko [here](https://github.com/MycroftAI/skill-homeassistant/issues/106#issuecomment-1289503539)

**Comment by stratus-ss** [comment]
@Tony763 how do we test this?

**Comment by Tony763** [comment]
Sadly, VK test did not catch this, as intent worked for it.  Only hint about something be wrong was wrote into log and I missed it:

https://github.com/MycroftAI/skill-homeassistant/blob/6cd09655aec11d08f147e92d5f5dfbe2f77d774f/70/mycroft/skills.log#L333-L362

**Comment by Tony763** [comment]
VK tests can be seen there: https://mycroftai.github.io/skill-homeassistant/70/

**Comment by Tony763** [comment]
I will rebase this with latest merged commits, so CI can check this, tonight.

**Comment by Tony763** [comment]
@stratus-ss or @krisgesling Could You add “Secure” label? I just rebased this PR to contain latest changes from 20.08 branch (CI should now work).

**Comment by Tony763** [comment]
Rebased, CI run in my repo was successful.

**Comment by Tony763** [comment]
Allure tests Ok, skill log OK, ready to go :rocket:

**Review by krisgesling — APPROVED** [review]

**Pull request merged**
