### PR TITLE
small error in settingsmeta.json and minor changes to readme.md

### PR DESCRIPTION
**Pull request by andlo**
## Description:
small error in settingsmeta.json and minor changes to readme.md including updating screenshots and add screenshot of long ived access token on home assistant.

**Related issue (if applicable):** fixes #<mycroft-homeassistant issue number goes here>

## Checklist:
  - [ ] Code is Python 3.x compatible
  - [ ] Travis is passing tests **Your PR cannot be merged unless tests pass**
  - [ ] No PEP Bot Errors or Issues

### CODE REVIEW

**Comment by andlo** [comment]
I think someone than me should merge this if it is OK

And I dont know how to submit it to market…..

**Comment by LinusSkucas** [comment]
I don't have collaborator access, so I can't merge the pr, but a few pieces of feedback:

The changes to the settings meta look fine.

The new images however, won't load. You need to add their url that GitHub has for that image, for it to display. For example, the home assistant image url would be: https://raw.githubusercontent.com/MycroftAI/mycroft-homeassistant/097a9d61f4d91786ce3c9ac06ba0c8b1dd007f01/home-assistant.png and you would put that url where `home-assistant.png` is in the readme.

I'm wondering if the settings meta.json file should be changed/ rewritten to be a YAML file, just for readability. I can do that once this is merged.

**Comment by andlo** [comment]
yah rewrite to .yaml would be nice....but not requered yet ;) But I could look into it and do the rewrite. 

The images do load fine from my place, and are made same way as I have done in other skills. So dont understand if they requere full path.

**Comment by LinusSkucas** [comment]
Huh. Weird. When I look at the rich diff the images show as being show as not found, but when I select view file, the new images are shown.

Either way, I think that the url is needed because the marketplace needs a url from which to display the icon/images.

**Comment by andlo** [comment]
That I dont understand, as my skills looks OK in market, and they dont have full url to image.

**Comment by LinusSkucas** [comment]
Huh. Okay, then everything looks good to me.

**Comment by andlo** [comment]
@LinusS1 I have acces to merge, but how to submit to market ? 

Should I clone this repo and not my own fork and submit that ?

**Comment by LinusSkucas** [comment]
Yeah, probably just cone this repo, then use msk submit

**Pull request merged**
