### PR TITLE
Divide dialogs for thermostat

### PR DESCRIPTION
**Pull request by Tony763**
#### Description
Divided dialogs for thermostat. This should fix issue #92.

#### Type of PR

_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
- [x] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Added Behave tests.

Tests pass when PR #109 is applied.

### CODE REVIEW

**Comment by Tony763** [comment]
When #109 will be merged, I will rebase this with it.

**Comment by Tony763** [comment]
Hi @krisgesling, this one was also rebased. All tests passed in my repo.
Please add “Secure” label, too.

**Comment by Tony763** [comment]
Allure tests Ok, skill log OK (tracker intent error only, fixed by #112), ready to go :rocket:

**Review by krisgesling — APPROVED** [review]
Awesome, thanks Tony!

**Pull request merged**
