### PR TITLE
updated examples section

### PR DESCRIPTION
**Pull request by pfefferle**
#### Description
Updated the examples section to represent the latest changes

#### Type of PR

- [ ] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [X] Documentation improvements
- [ ] Test improvements

### CODE REVIEW

**Comment by stratus-ss** [comment]
Thanks for the PR, can you explain why you are requesting these updates?

**Comment by pfefferle** [comment]
hey @stratus-ss if I remember correctly, we had comments in issues, that not every action in the examples section works, so I checked them and tried to update to the "new" and working versions and/or removed them:

* "Read bedroom temperature" is no longer working
* "Turn on the office light" does no longer support the "the"
* "Turn on on the AC" had a typo and I am not sure if it still works

**Comment by stratus-ss** [comment]
Thanks for the reply. I appreciate the update. It just wasn't clear before.

I am going to merge this, assuming your testing is correct (my mark ii is currently out of commission)

**Review by stratus-ss — APPROVED** [review]

**Comment by pfefferle** [comment]
I will try to be a bit more descriptive in the next PR.

Thanks for merging!

**Pull request merged**
