### PR TITLE
Updated translations

### PR DESCRIPTION
**Pull request by devs-mycroft**
Automatically generated PR from translate.mycroft.ai

The updated languages are:
- sv-se
- de-de
- fr-fr
- es-es
- es-lm
- nl-nl
- pt-br
- it-it
- da-dk

### CODE REVIEW

**Review by Raukze — CHANGES_REQUESTED** [review]
In file dialog/de-de/homeassistant.error.setup.dialog there is a typo. "Hone" needs to get changed to "Home".

**Comment by stratus-ss** [comment]
This PR is blocked until the conflicts are resolved

**Comment by forslund** [comment]
Gonna do a new Translation pull from https://translate.mycroft.ai. The translations are based on the version in mycroft-skills repo so it may or may not fix things.

I am a bit curious about the conflict in __init__.py and the readme since the PR only touches the vocab files.

**Comment by forslund** [comment]
Maybe some issue with branches currently active and the branch submitted to the mycroft-skills repo?

**Comment by forslund** [comment]
Closing this for now. Seems like another PR was merged already.

**Pull request closed without merging**
