### PR TITLE
Issue #63: STT engine return percentage as symbol

### PR DESCRIPTION
**Pull request by Tony763**
#### Description
fix issue #63 - intent to set light brightness percentage, STT return percentage as symbol
Updated all languages

#### Type of PR
- [x] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

### CODE REVIEW

**Comment by stratus-ss** [comment]
LGTM although pending testing. Hopefully I can get to this tonight, although I don't forsee any problems

**Comment by stratus-ss** [comment]
i'll put some effort around this this week. Sorry for the delay

**Comment by stratus-ss** [comment]
@Tony763 the tests are failing. This change requires a change to 
```
/opt/mycroft/skills/homeassistant.mycroftai/test/intent/016.SetLightBrightUnknown.intent.json
/opt/mycroft/skills/homeassistant.mycroftai/test/intent/006.SetLightBright.intent.json
```

When I edited these the tests pass and I can confirm the the light still changes

Please make the changes to the tests and I will merge this

**Comment by Tony763** [comment]
Hi @stratus-ss  sorry for the delay, I missed notification. Old tests fixed. VK tests will be added in tests refactor.

**Comment by krisgesling** [comment]
Hey Tony, can you check these conflicts from the last PR getting merged? Seems like this one is good to go otherwise

**Comment by Tony763** [comment]
Hi @krisgesling , conflicts solved, ready to go.

**Pull request merged**
